[build]
  # Directory with the lambda functions to deploy to AWS.
  functions = "build/faas"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
